on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: Node 18.13
      uses: actions/setup-node@v1
      with:
        node-version: 18.13

    - name: Set up environment file
      run: |
        mkdir -p src/environments
        echo "export const environment = {
          production: true,
          baseURL: '${{ secrets.BASE_URL }}',
          imprintName: '${{ secrets.IMPRINT_NAME }}',
          imprintStreet: '${{ secrets.IMPRINT_STREET }}',
          imprintCity: '${{ secrets.IMPRINT_CITY }}',
          imprintPhone: '${{ secrets.IMPRINT_PHONE }}',
          imprintEmail: '${{ secrets.IMPRINT_EMAIL }}',
        };" > src/environments/environment.ts

    - name: Install and build
      run: |
        npm i
        npm run build --base-href="/"

    - name: Run tests
      run: |
        npm run test -- --watch=false --browsers=ChromeHeadless

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.FTP_URL }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/videoflix-frontend/browser/