on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: Node 18.13
      uses: actions/setup-node@v1
      with:
        node-version: 18.13

    - name: Install and build
      run: |
        npm i
        npm run build --configuration production --base-href="/"

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.FTP_URL }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/videoflix-frontend/browser/